using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;
using System.Text;
using System.Threading.Tasks;

namespace StructGen.Objects
{
    public class GeneratorInterface
    {
        /// <summary>enum for available header types that can be created</summary>
        public enum HEADER_TYPE
        {
            C,
            CPP,
            CSHARP,
        }

        readonly static string fileHeader =
        "/////////////////////////////////////////////////////////////////\r\n" +
        "//! This file is auto-generated by StructGen \r\n" +
        "/////////////////////////////////////////////////////////////////\r\n\n";

        /// <summary>enum for acceptable variable types</summary>
        static readonly List<string> validTypes = new List<string>
        {
            "int",
            "int8_t",
            "int16_t",
            "int32_t",
            "unsigned int",
            "uint",
            "uint8_t",
            "uint16_t",
            "uint32_t",
            "float",
            "double",
            "string",
            "char",
            "unsigned char",
            "signed char",
        };

        /// <summary>Handles CSV file input</summary>
        /// <param name="file"> -[out]- output of the parsed file data as a structrue</param>
        /// <returns></returns>
        public static int HandleCsvFile(ref File file)
        {
            file = new File();
            return 0;
        }

        /// <summary>Handles JSON file input</summary>
        /// <param name="file"> -[out]- output of the parsed file data as a structrue</param>
        /// <returns></returns>
        public static int HandleJsonFile(ref File file)
        {
            file = new File();
            return 0;
        }

        /// <summary>Handles XML file input</summary>
        /// <param name="file"> -[out]- output of the parsed file data as a structrue</param>
        /// <returns></returns>
        public static int HandleXmlFile(ref File file)
        {
            file = new File();
            return 0;
        }

        /// <summary>Function to create a desired header file</summary>
        /// <param name="type"> -[in]- Type of header file to be created</param>
        /// <param name="file"> -[in]- File structure to be created</param>
        /// <returns></returns>
        public static string CreateHeaderFile(HEADER_TYPE type, File file)
        {
            return type switch
            {
                HEADER_TYPE.C => GenerateHeaderC(file),
                HEADER_TYPE.CPP => GenerateHeaderCPP(file),
                HEADER_TYPE.CSHARP => GenerateHeaderCSHARP(file),
                _ => "Error!",
            };
        }

        /// <summary>Validates the variables in a file structure are acceptable</summary>
        /// <param name="file"> -[in]- File structure to be validated</param>
        /// <returns>A list of variable names with improper types</returns>
        private static List<string> ValidateVariableTypes(File file)
        {
            List<string> invalidVariables = new List<string>();

            foreach (var structure in file.Structures)
            {
                foreach (var variable in structure.Variables)
                {
                    if (!validTypes.Contains(variable.Type))
                    {
                        invalidVariables.Add(variable.Name);
                    }
                }
            }

            return invalidVariables;
        }

        /// <summary>Creates a header for C language</summary>
        /// <param name="file"> -[in]- File structure to be created</param>
        /// <returns>string of output file content</returns>
        private static string GenerateHeaderC(File file)
        {
            StringBuilder output = new StringBuilder();

            output.AppendLine(fileHeader);

            List<string> invalidVars = ValidateVariableTypes(file);

            if (invalidVars.Count == 0)
            {
                foreach (var structure in file.Structures)
                {
                    // Define the structure
                    output.AppendLine($"/* {structure.Comment} */");
                    output.AppendLine($"struct {structure.Name}");
                    output.AppendLine("{");

                    // Define variables
                    foreach (var variable in structure.Variables)
                    {
                        output.AppendLine($"    {variable.Type} {variable.Name}; /* {variable.Comment} */");
                    }

                    // Close the structure definition
                    output.AppendLine("};\n\n");
                }
            }
            else
            {
                // respond with which variables are invalid
                output.AppendLine("\n\nBad input file variable types on variables:\n");

                foreach (var invalidVar in invalidVars)
                {
                    output.AppendLine(invalidVar);
                }
            }

            return output.ToString();
        }

        /// <summary>Creates a header for C++ language</summary>
        /// <param name="file"> -[in]- File structure to be created</param>
        /// <returns>string of output file content</returns>
        private static string GenerateHeaderCPP(File file)
        {
            StringBuilder output = new StringBuilder();

            output.AppendLine(fileHeader);
            output.AppendLine("#include <string>");
            output.AppendLine("#include <cstdint>");
            output.AppendLine("\n\n");

            List<string> invalidVars = ValidateVariableTypes(file);

            if (invalidVars.Count == 0)
            {
                foreach (var structure in file.Structures)
                {
                    // Define the structure
                    output.AppendLine($"/// @brief {structure.Comment}");
                    output.AppendLine($"struct {structure.Name}");
                    output.AppendLine("{");

                    // Define variables
                    foreach (var variable in structure.Variables)
                    {
                        output.AppendLine($"    {variable.Type} {variable.Name}; // {variable.Comment}");
                    }

                    // Close the structure definition
                    output.AppendLine("};\n\n");
                }
            }
            else
            {
                // respond with which variables are invalid
                output.AppendLine("\n\nBad input file variable types on variables:\n");

                foreach (var invalidVar in invalidVars)
                {
                    output.AppendLine(invalidVar);
                }
            }

            return output.ToString();
        }

        /// <summary>Creates a header for C# language</summary>
        /// <param name="file"> -[in]- File structure to be created</param>
        /// <returns>string of output file content</returns>
        private static string GenerateHeaderCSHARP(File file)
        {
            StringBuilder output = new StringBuilder();

            output.AppendLine(fileHeader);
            output.AppendLine("using System;");
            output.AppendLine("using System.Runtime.InteropServices;");
            output.AppendLine("\n");

            List<string> invalidVars = ValidateVariableTypes(file);

            if (invalidVars.Count == 0)
            {
                foreach (var structure in file.Structures)
                {
                    // Define the structure 
                    output.AppendLine($"/// <summary> {structure.Comment} </summary>");
                    output.AppendLine($"[StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]");
                    output.AppendLine($"public struct {structure.Name}");
                    output.AppendLine("{");

                    // Define variables
                    foreach (var variable in structure.Variables)
                    {
                        output.AppendLine($"    public {variable.Type} {variable.Name}; // {variable.Comment}");
                    }

                    // Close the structure definition
                    output.AppendLine("}\n");
                }
            }
            else
            {
                // respond with which variables are invalid
                output.AppendLine("\n\nBad input file variable types on variables:\n");

                foreach (var invalidVar in invalidVars)
                {
                    output.AppendLine(invalidVar);
                }
            }

            return output.ToString();
        }

        private static void GenerateFileDescriptionDocument(File file)
        {
            // @todo
        }
    }
}
